# -*- coding: utf-8 -*-
"""ActividadCetaceo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEYIcAHdm6sO0mEkhNwcfhxnTTIV4ct1
"""
#prueba en git
class Mamifero:
  def __init__(self, cantMamas, esperanzaDeVida):
    self.cantMamas = cantMamas
    self.__esperanzaDeVida = esperanzaDeVida

  def mamar(self):
    print("Esta alimentandose")

  def nacer():
    print("esta naciendo")

  def __str__(self):
    return f"Esperanza de vida de {self.__esperanzaDeVida} años y tiene {self.cantMamas} mama." 

  def get_esperanzaDeVida(self):
    return self.__esperanzaDeVida

  def set_esperanzaDeVida(self, esperanzaDeVida):
    self.__esperanzaDeVida = esperanzaDeVida    

class AnimalMarino:
  def __init__(self, tieneBranqueas, especie):
    self.__tieneBranqueas = tieneBranqueas
    self.__especie = especie

  def nadar(self):
    print("esta nadando...")

  def __str__(self):
    return f"La {self.__especie} es unos de los animales marinos mas grandes, tiene {self.__tieneBranqueas} no tiene branqueas."

  def get_tieneBranqueas(self):
    return self.__tieneBranqueas

  def set_tieneBranqueas(self, tieneBranqueas):
    self.__tieneBranqueas = tieneBranqueas

  def get_especie(self):
    return self.__especie

  def set_especie(self, especie):
    self.__especie = especie 

class Cetaceo(Mamifero, AnimalMarino):
  def __init__(self, cantMamas, esperanzaDeVida, tieneBranqueas, especie, notas, viveEn, peso):

    Mamifero.__init__(self, cantMamas, esperanzaDeVida )
    AnimalMarino.__init__(self, tieneBranqueas, especie)
       
    self.__notas = notas
    self.__viveEn = viveEn
    self.__peso = peso

  def __str__(self):
    return  Mamifero.__str__(self) + "\n" + AnimalMarino.__str__(self) + f"\nEste Cetaceo puede medir mas de {self.__notas} metros, vive en el {self.__viveEn} y su peso puede ser hasta de {self.__peso} toneladas." 

cetaceo1 =  Cetaceo(1, 80, "pulmones", "Ballena azul", 29, "oceano pacifico", 180)  

print(f"{cetaceo1}")